export const STATES_SEED: { name: string }[] = [
    { "name": "Capital Federal" },
    { "name": "Buenos Aires" },
    { "name": "Catamarca" },
    { "name": "Córdoba" },
    { "name": "Corrientes" },
    { "name": "Chaco" },
    { "name": "Chubut" },
    { "name": "Entre Ríos" },
    { "name": "Formosa" },
    { "name": "Jujuy" },
    { "name": "La Pampa" },
    { "name": "La Rioja" },
    { "name": "Mendoza" },
    { "name": "Misiones" },
    { "name": "Neuquén" },
    { "name": "Río Negro" },
    { "name": "Salta" },
    { "name": "San Juan" },
    { "name": "San Luis" },
    { "name": "Santa Cruz" },
    { "name": "Santa Fe" },
    { "name": "Santiago del Estero" },
    { "name": "Tierra del Fuego" },
    { "name": "Tucumán" },
]