export const PRODUCTS_CONSTANTS = {
    INCREMENT_AMOUNT_LIMIT: 10,
    DEFAULT_LIMIT: 10,
    INSTALLMENTS: {
        '6_WHITOUHT_INTEREST': 6,
        '12_WHITOUHT_INTEREST': 12,
        '18_WHITOUHT_INTEREST': 18,
        '24_WHITOUHT_INTEREST': 24,
    }
}